import type { CatalogSchema, MessageSchema, ParamType } from '../artifact.js';
import { ParamKind } from '../artifact.js';
import { LinguiniError } from '../errors.js';
import { hashSubset } from './schema.js';
import type { BindingsTarget, LinguiniConfig } from './config.js';

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

type BindingsOptions = Omit<NonNullable<LinguiniConfig['bindings']>, 'out' | 'targets'> & {
    out?: string;
};

/**
 * Generates the typed bindings module: `createMessages(lx)` returning a nested tree of typed
 * accessor functions, plus the schemaHash the tree was generated against. Bindings carry types
 * and keys only — message content stays in the hot-swappable artifact.
 */
export function generateBindings(
    schema: CatalogSchema,
    schemaHash: string,
    options: BindingsOptions = { out: '' }
): string {
    const runtimeImport = options.runtimeImport ?? 'linguini';
    const typeImports = collectTypeImports(schema, options.types ?? {});

    const lines: string[] = [];
    lines.push('/* eslint-disable */');
    lines.push('// Generated by linguini. Do not edit — run `linguini compile` to regenerate.');
    lines.push(`import type { Linguini } from '${runtimeImport}';`);
    for (const [specifier, names] of typeImports) {
        lines.push(`import type { ${[...names].sort().join(', ')} } from '${specifier}';`);
    }
    lines.push('');
    lines.push(`export const schemaHash = '${schemaHash}';`);
    lines.push('');
    lines.push('export function createMessages(lx: Linguini) {');
    lines.push('    return {');
    renderTree(buildTree(schema), lines, 2, options.types ?? {});
    lines.push('    };');
    lines.push('}');
    lines.push('');
    return lines.join('\n');
}

/**
 * Generates a per-target subset module (design §14.3): `createMessages(lx)` over exactly the
 * target's keys, plus `schemaSubset` (key → schema hash) and `subsetHash`. Consumers register
 * the subset with the runtime so hot-swapped artifacts are validated against only the keys
 * this module can actually render.
 */
export function generateTargetBindings(
    schema: CatalogSchema,
    keySchemaHashes: { [key: string]: string },
    target: BindingsTarget,
    subsetKeys: readonly string[],
    shared: BindingsOptions = {}
): string {
    if (subsetKeys.length === 0) {
        throw new LinguiniError(`bindings target "${target.name}" resolved to zero keys`);
    }
    const subsetSchema: CatalogSchema = {};
    const schemaSubset: { [key: string]: string } = {};
    for (const key of subsetKeys) {
        const messageSchema = schema[key];
        const sigHash = keySchemaHashes[key];
        if (!messageSchema || !sigHash) {
            throw new LinguiniError(`bindings target "${target.name}": unknown key "${key}"`);
        }
        subsetSchema[key] = messageSchema;
        schemaSubset[key] = sigHash;
    }
    const options: BindingsOptions = {
        runtimeImport: target.runtimeImport ?? shared.runtimeImport,
        types: target.types ?? shared.types,
    };
    const runtimeImport = options.runtimeImport ?? 'linguini';
    const typeImports = collectTypeImports(subsetSchema, options.types ?? {});

    const lines: string[] = [];
    lines.push('/* eslint-disable */');
    lines.push('// Generated by linguini. Do not edit — run `linguini compile` to regenerate.');
    lines.push(`// Bindings target: ${target.name} (${subsetKeys.length} keys)`);
    lines.push(`import type { Linguini } from '${runtimeImport}';`);
    for (const [specifier, names] of typeImports) {
        lines.push(`import type { ${[...names].sort().join(', ')} } from '${specifier}';`);
    }
    lines.push('');
    lines.push(`export const subsetHash = '${hashSubset(schemaSubset)}';`);
    lines.push('');
    lines.push('export const schemaSubset: { [key: string]: string } = {');
    for (const key of Object.keys(schemaSubset).sort()) {
        lines.push(`    '${key}': '${schemaSubset[key]}',`);
    }
    lines.push('};');
    lines.push('');
    lines.push('export function createMessages(lx: Linguini) {');
    lines.push('    return {');
    renderTree(buildTree(subsetSchema), lines, 2, options.types ?? {});
    lines.push('    };');
    lines.push('}');
    lines.push('');
    return lines.join('\n');
}

type Tree = Map<string, Tree | { key: string; schema: MessageSchema }>;

function buildTree(schema: CatalogSchema): Tree {
    const root: Tree = new Map();
    for (const key of Object.keys(schema).sort()) {
        const segments = key.split('.');
        const leafName = segments.pop()!;
        let node = root;
        for (const segment of segments) {
            let next = node.get(segment);
            if (!(next instanceof Map)) {
                next = new Map();
                node.set(segment, next);
            }
            node = next;
        }
        node.set(leafName, { key, schema: schema[key]! });
    }
    return root;
}

function renderTree(
    tree: Tree,
    lines: string[],
    depth: number,
    types: { [typeName: string]: string }
): void {
    const indent = '    '.repeat(depth);
    for (const [name, node] of tree) {
        const prop = IDENTIFIER.test(name) ? name : `'${name}'`;
        if (node instanceof Map) {
            lines.push(`${indent}${prop}: {`);
            renderTree(node, lines, depth + 1, types);
            lines.push(`${indent}},`);
        } else {
            lines.push(`${indent}${prop}: ${renderAccessor(node.key, node.schema, types)},`);
        }
    }
}

function renderAccessor(
    key: string,
    schema: MessageSchema,
    types: { [typeName: string]: string }
): string {
    let returnType = 'string';
    if (schema.typeName !== undefined) {
        const mapping = types[schema.typeName];
        returnType = mapping ? typeNameOf(mapping) : 'unknown';
    }
    const paramNames = Object.keys(schema.params).sort();
    if (paramNames.length === 0) {
        return `(locale: string) => lx.format('${key}', locale) as ${returnType}`;
    }
    const paramsType = paramNames
        .map(name => {
            const prop = IDENTIFIER.test(name) ? name : `'${name}'`;
            return `${prop}: ${tsTypeOf(schema.params[name]!)}`;
        })
        .join('; ');
    return `(locale: string, params: { ${paramsType} }) => lx.format('${key}', locale, params) as ${returnType}`;
}

function tsTypeOf(param: ParamType): string {
    switch (param.type) {
        case ParamKind.STRING:
            return 'string | number';
        case ParamKind.NUMBER:
            return 'number';
        case ParamKind.DATETIME:
            return 'Date | number';
        case ParamKind.LIST:
            return 'readonly string[]';
        case ParamKind.SELECT:
            return param.branches.map(branch => `'${branch}'`).join(' | ');
    }
}

/** `"./embed-types.js#LangEmbed"` → import `LangEmbed` from `./embed-types.js`. */
function collectTypeImports(
    schema: CatalogSchema,
    types: { [typeName: string]: string }
): Map<string, Set<string>> {
    const usedTypeNames = new Set(
        Object.values(schema)
            .map(messageSchema => messageSchema.typeName)
            .filter((name): name is string => name !== undefined)
    );
    const imports = new Map<string, Set<string>>();
    for (const typeName of usedTypeNames) {
        const mapping = types[typeName];
        if (!mapping) {
            continue;
        }
        const [specifier] = mapping.split('#');
        const exportName = typeNameOf(mapping);
        const names = imports.get(specifier!) ?? new Set();
        names.add(exportName);
        imports.set(specifier!, names);
    }
    return imports;
}

function typeNameOf(mapping: string): string {
    const hash = mapping.indexOf('#');
    return hash === -1 ? mapping : mapping.slice(hash + 1);
}
