import { assert, expect } from 'chai';
import path from 'path';

import { Linguini, LinguiniError } from '../../src';

/**
 * Example generated type schema (would normally be auto-generated by CLI)
 */
type TestTranslations = {
    prompts: {
        greeting: string;
        farewell: string;
        colorInfo: string;
    };
    info: {
        about: {
            title: string;
            description: string;
        };
        contact: {
            email: string;
            github: string;
        };
    };
    validation: {
        errors: {
            required: string;
            minLength: string;
            maxLength: string;
            email: string;
            custom: {
                birthday: string;
            };
        };
        warnings: {
            almostExpired: string;
            lowCredits: string;
        };
    };
};

describe('Linguini v2', (): void => {
    describe('Locale Folder Structure', (): void => {
        const localeFolderPath = path.join(__dirname, './data-v2/locale-folder');
        let linguini: Linguini<TestTranslations>;

        before(() => {
            linguini = new Linguini<TestTranslations>(localeFolderPath);
        });

        describe('#constructor()', (): void => {
            it('should auto-detect locale-folder structure', (): void => {
                const locales = linguini.getLocales();
                expect(locales).to.include('en-US');
                expect(locales).to.include('es-MX');
            });

            it('should load multiple locales', (): void => {
                expect(linguini.hasLocale('en-US')).to.be.true;
                expect(linguini.hasLocale('es-MX')).to.be.true;
                expect(linguini.hasLocale('fr-FR')).to.be.false;
            });
        });

        describe('#t() - Type-safe translations', (): void => {
            it('should get simple translation', (): void => {
                const greeting = linguini.t('prompts.greeting', 'en-US', { NAME: 'Alice' });
                expect(greeting).to.equal('Happy birthday, Alice! 🎂');
            });

            it('should get nested translation', (): void => {
                const title = linguini.t('info.about.title', 'en-US');
                expect(title).to.equal('About Us');
            });

            it('should get deeply nested translation', (): void => {
                const error = linguini.t('validation.errors.custom.birthday', 'en-US');
                expect(error).to.equal('Please enter a valid birthday date');
            });

            it('should replace variables', (): void => {
                const error = linguini.t('validation.errors.minLength', 'en-US', { MIN: '5' });
                expect(error).to.equal('Must be at least 5 characters');
            });

            it('should work with different locales', (): void => {
                const enGreeting = linguini.t('prompts.greeting', 'en-US', { NAME: 'Alice' });
                const esGreeting = linguini.t('prompts.greeting', 'es-MX', { NAME: 'Alice' });

                expect(enGreeting).to.equal('Happy birthday, Alice! 🎂');
                expect(esGreeting).to.equal('¡Feliz cumpleaños, Alice! 🎂');
            });

            it('should throw for invalid locale', (): void => {
                expect(() => linguini.t('prompts.greeting', 'invalid')).to.throw(
                    LinguiniError,
                    'Invalid locale: invalid'
                );
            });

            it('should throw for invalid key', (): void => {
                expect(() => linguini.t('invalid.key', 'en-US')).to.throw(
                    LinguiniError,
                    'Invalid translation key: invalid.key'
                );
            });
        });

        describe('#ref() - Reference strings', (): void => {
            it('should get reference string', (): void => {
                const term = linguini.ref('terms.birthday', 'en-US');
                expect(term).to.equal('birthday');
            });

            it('should get Spanish reference', (): void => {
                const term = linguini.ref('terms.birthday', 'es-MX');
                expect(term).to.equal('cumpleaños');
            });

            it('should throw for invalid reference', (): void => {
                expect(() => linguini.ref('invalid.ref', 'en-US')).to.throw(
                    LinguiniError,
                    'Invalid reference key: invalid.ref'
                );
            });
        });

        describe('#common() - Common values', (): void => {
            it('should get common color', (): void => {
                const color = linguini.common('colors.primary');
                expect(color).to.equal('#FF5733');
            });

            it('should get common link', (): void => {
                const link = linguini.common('links.github');
                expect(link).to.equal('https://github.com/KevinNovak');
            });

            it('should get common emoji', (): void => {
                const emoji = linguini.common('emojis.cake');
                expect(emoji).to.equal('🎂');
            });

            it('should throw for invalid common key', (): void => {
                expect(() => linguini.common('invalid.key')).to.throw(
                    LinguiniError,
                    'Invalid common key: invalid.key'
                );
            });
        });

        describe('#has() - Key existence check', (): void => {
            it('should return true for existing key', (): void => {
                expect(linguini.has('prompts.greeting', 'en-US')).to.be.true;
            });

            it('should return false for non-existing key', (): void => {
                expect(linguini.has('invalid.key', 'en-US')).to.be.false;
            });

            it('should return false for invalid locale', (): void => {
                expect(linguini.has('prompts.greeting', 'invalid')).to.be.false;
            });
        });

        describe('Variable replacement with refs and common', (): void => {
            it('should resolve REF: variables', (): void => {
                const farewell = linguini.t('prompts.farewell', 'en-US', { NAME: 'Bob' });
                expect(farewell).to.equal('Goodbye, Bob! Thank you for using our service!');
            });

            it('should resolve COM: variables', (): void => {
                const colorInfo = linguini.t('prompts.colorInfo', 'en-US');
                expect(colorInfo).to.equal('Your theme color is #FF5733');
            });

            it('should resolve nested refs in validation', (): void => {
                const error = linguini.t('validation.errors.custom.birthday', 'es-MX');
                expect(error).to.equal('Por favor ingrese una fecha de cumpleaños válida');
            });
        });
    });

    describe('Locale in Filename Structure', (): void => {
        const localeInFilenamePath = path.join(__dirname, './data-v2/locale-in-filename');
        let linguini: Linguini;

        before(() => {
            linguini = new Linguini(localeInFilenamePath);
        });

        describe('#constructor()', (): void => {
            it('should auto-detect locale-in-filename structure', (): void => {
                const locales = linguini.getLocales();
                expect(locales).to.include('en-US');
            });
        });

        describe('#t() - Translations', (): void => {
            it('should get flat translation', (): void => {
                const greeting = linguini.t('prompts.greeting', 'en-US', { NAME: 'Alice' });
                expect(greeting).to.equal('Happy birthday, Alice!');
            });

            it('should get nested translation from subdirectory', (): void => {
                const error = linguini.t('validation.errors.required', 'en-US');
                expect(error).to.equal('This field is required');
            });

            it('should handle deeply nested key', (): void => {
                const title = linguini.t('info.about.title', 'en-US');
                expect(title).to.equal('About Us');
            });
        });
    });

    describe('Legacy API Compatibility', (): void => {
        const legacyPath = path.join(__dirname, './data');
        let linguini: Linguini;

        before(() => {
            // Using legacy constructor
            linguini = new Linguini(legacyPath, 'lang');
        });

        describe('#get() - Deprecated', (): void => {
            it('should still work with type mapper', (): void => {
                const { TypeMappers } = require('../../src');
                const line = linguini.get('intro.myGitHub', 'en', TypeMappers.String);
                expect(line).to.equal('My GitHub is: https://github.com/KevinNovak');
            });
        });

        describe('#getRaw() - Deprecated', (): void => {
            it('should return raw JSON', (): void => {
                const json = linguini.getRaw('regexes.hello', 'en');
                expect(json.pattern).to.equal('hello');
            });

            it('should handle variables', (): void => {
                const greeting = linguini.getRaw('intro.greeting', 'en', {
                    FIRST_NAME: 'Bruce',
                    LAST_NAME: 'Wayne',
                });
                expect(greeting).to.equal('Hello, nice to meet you Bruce Wayne!');
            });
        });

        describe('#getRef() - Deprecated', (): void => {
            it('should get reference', (): void => {
                const ref = linguini.getRef('aboutMe.favoriteColor', 'en');
                expect(ref).to.equal('Blue');
            });
        });

        describe('#getCom() - Deprecated', (): void => {
            it('should get common value', (): void => {
                const com = linguini.getCom('links.github');
                expect(com).to.equal('https://github.com/KevinNovak');
            });
        });
    });

    describe('Explicit Folder Structure Option', (): void => {
        it('should use locale-folder when specified', (): void => {
            const localeFolderPath = path.join(__dirname, './data-v2/locale-folder');
            const linguini = new Linguini(localeFolderPath, {
                folderStructure: 'locale-folder',
            });

            expect(linguini.getLocales()).to.include('en-US');
            expect(linguini.t('prompts.greeting', 'en-US', { NAME: 'Test' })).to.include('Test');
        });

        it('should use locale-in-filename when specified', (): void => {
            const localeInFilenamePath = path.join(__dirname, './data-v2/locale-in-filename');
            const linguini = new Linguini(localeInFilenamePath, {
                folderStructure: 'locale-in-filename',
            });

            expect(linguini.getLocales()).to.include('en-US');
        });
    });
});


